[bumpversion]
current_version = "0.1.2"
commit = false
tag = false

[[bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[bumpversion.parts]
major = { first_value = 0 }
minor = { first_value = 1 }
patch = { first_value = 0 }
